### ISSUE TITLE
How to use DC Service SDK?

### ISSUE THREAD

**Issue by cipher135** [adobe/pdftools-java-sdk-samples#4]
What is DC Services SDK? Is it an API? How to use it to make my own application? I downloaded the sample code from **Get Started** section. I want to use it to generate PDF from Static HTML zip. When I run the sample, it converts input files that are located in the resources folder. I changed the code of **CreatePDFFromStaticHTML.java**, which has a _main_ method, to take input and packaged it. When I run it, it says **no main manifest attribute available**. It's been more than 5 days (continuously) and I am still stuck and frustrated. Please Help Me With This.

- A Novice Enthusiastic Developer

**Comment by pulkit-maheshwr** [comment]
@cipher135 : Thanks for trying out the DC Services SDK. For more details, you could refer to the following link:
[https://www.adobe.io/apis/documentcloud/dcsdk/docs.html](https://www.adobe.io/apis/documentcloud/dcsdk/docs.html)

Could you please help us with the following details so that we can figure out the exact problem?
1) How you are running the Samples?
2) How you have structured the input zip file?

**Comment by cipher135** [comment]
Thank your @pulkit-maheshwr for replying. Let me answer your queries as far as I can.
1. I downloaded the sample zip file from where I created credentials. Unzipped it and run with the following command:
 mvn -f pom.xml exec:java -Dexec.mainClass=com.adobe.platform.operation.samples.createpdf.CreatePDFFromStaticHTML 
because I had to try for Static HTML. It run smoothly with no error and generated a PDF for the same in the target folder. 

2. Now I want to use the services only for converting static HTML files to PDF so, I deleted the extra source codes which were for like, DOCx, PPT, Combining PDFs, exporting to another format, etc. Then I modified the source code of CreatePDFFromStaticHTML.java to provide the path of the input file and the output directory and file name.
I packaged the file using  the command,   **$ mvn package** 
When I run the jar file it says no main manifest attribute available. 
I am using these types of services for the first time. So, I might be missing something big. Your effort will be a great help. 
Thank you for your time.

**Comment by pulkit-maheshwr** [comment]
The possible reason is the way you are packaging the Samples code in the JAR file. And running the JAR directly without creating an executable JAR file. For an executable JAR file, it must have a manifest file with a Main-Class attribute in it.

1. Add the following maven plugin in your pom.xml file.
`      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <mainClass>com.adobe.platform.operation.samples.createpdf.CreatePDFFromStaticHTML</mainClass>
            </manifest>
          </archive>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
        <executions>
          <execution>
            <id>assemble-all</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>`

2.  Run `mvn  clean package`.
3.  `cd target; java -jar dc-services-sdk-samples-1.0.0-jar-with-dependencies.jar`

**Comment by pulkit-maheshwr** [comment]
Closing this issue because it has been inactive for 2 months.
